[build]
  publish = "image-gallery"
  command = "gatsby build"
  environment = { GATSBY_CPU_COUNT = "1", GATSBY_CONCURRENT_DOWNLOAD = "15" }

[[plugins]]
  package = "@netlify/plugin-gatsby"

 from = "/*"
  to = "/"
  status = 200